[dimensions]
; values in mm
width = 250.0
height = 250.0
depth = 250.0

[speed]
; values in mm/s^2
inner_wall = 50.0
outer_wall = 50.0
infill = 60.0
support = 40.0

[other]
; nozzle size in mm
nozzle_size = 0.4

; how much overhang in degrees the printer can handle before supports needed
overhang_tolerance = 45.0
 
