[dimensions]
; values in mm
width = 250.0
height = 250.0
depth = 250.0

[speed]
; values in mm/s^2
shell = 20.0
infill = 20.0
support = 20.0

[other]
; how much overhang in degrees the printer can achieve before supports needed
overhang_tolerance = 1.0
 
